select SNO,SNAME,to_char(SDATE,'YYYY') from tb_student;
select SNO,SNAME,SHIGH from tb_student where SAGE=18 AND to_char(SDATE,'YYYY')=2012 ;
select SNO,SNAME from tb_student where SHIGH/100.0 BETWEEN 1.7 AND 1.85 ;
SELECT * FROM TB_STUDENT;
select SNO,SNAME from tb_student where SNAME LIKE '张%' AND SSEX='M';
select DECODE(SSEX,'M','男','F','女')性别,count(sno) from TB_STUDENT  group by SSEX;
select ST.SNO,SNAME,to_char(SDATE,'YYYY'),DECODE(SCLASS,'1','一班','2','二班','3','三班')班级 FROM TB_STUDENT ST,TB_COURSE CO,TB_SCORE SC WHERE CO.CTEACHER='周洪波' AND SC.CNO=CO.CNO AND ST.SNO=SC.SNO order by to_char(SDATE,'YYYY') DEsc;
SELECT * FROM TB_COURSE;
SELECT * FROM TB_SCORE;
SELECT DECODE(SCLASS,'1','一班','2','二班','3','三班','','无班')班级,COUNT(SNO)人数 FROM TB_STUDENT GROUP BY SCLASS;
SELECT DECODE(SCLASS,'1','一班','2','二班','3','三班','','无班')班级,AVG(SCORE)数学成绩的平均分 FROM TB_STUDENT ST,TB_SCORE SC,TB_COURSE CO WHERE SC.CNO=CO.CNO AND CO.CNAME='数学' AND ST.SNO=SC.SNO GROUP BY SCLASS;
insert into TB_SCORE(sno,cno,score) values(1004,1,32);
SELECT to_char(sdate,'YYYY')年级,DECODE(SSEX,'F','F','M','M')性别,COUNT(SNO)FROM TB_STUDENT GROUP BY to_char(sdate,'YYYY'),SSEX order by to_char(SDATE,'YYYY') DEsc;
SELECT ST.SNO,SNAME,CO.CNAME,SC.SCORE FROM TB_STUDENT ST,TB_COURSE CO,TB_SCORE SC WHERE SC.SCORE<60 AND SC.CNO=CO.CNO AND ST.SNO=SC.SNO;
SELECT ST.SNO,SNAME,CO.CNAME,SC.SCORE,DECODE(SCLASS,'1','一班','2','二班','3','三班','','无班')班级 FROM TB_STUDENT ST,TB_COURSE CO,TB_SCORE SC WHERE SC.SCORE<60 AND SC.CNO=CO.CNO AND ST.SNO=SC.SNO AND CNAME='数学';
SELECT SNAME,COUNT(ST.SNO) FROM TB_STUDENT ST,TB_SCORE SC WHERE ST.SNO=SC.SNO AND SC.SCORE>60 GROUP BY SNAME;
create view v_student_2012 as  
(SELECT DECODE(SCLASS,'1','一班','2','二班','3','三班','','无班')班级,COUNT(SNO)人数 FROM TB_STUDENT GROUP BY SCLASS);
SELECT * FROM v_student_2012;
create view v_student_2013 as  
(SELECT ST.SNO,SNAME,CO.CNAME,SC.SCORE FROM TB_STUDENT ST,TB_COURSE CO,TB_SCORE SC WHERE SC.SCORE<60 AND SC.CNO=CO.CNO AND ST.SNO=SC.SNO);
SELECT * FROM v_student_2013;
create view v_student_2014 as  
(SELECT ST.SNO,SNAME,CO.CNAME,SC.SCORE,DECODE(SCLASS,'1','一班','2','二班','3','三班','','无班')班级 FROM TB_STUDENT ST,TB_COURSE CO,TB_SCORE SC WHERE SC.SCORE<60 AND SC.CNO=CO.CNO AND ST.SNO=SC.SNO AND CNAME='数学');
SELECT * FROM v_student_2014;
UPDATE TB_STUDENT SET SAGE=SAGE+1;
UPDATE TB_SCORE SET SCORE=SCORE+8;
DELETE FROM TB_STUDENT WHERE SCLASS is null;
DELETE FROM TB_STUDENT WHERE to_char(SDATE,'YYYY')='2013';